In [2]:
import pandas as pd

In [64]:
df = pd.read_csv("cinetica_equilibrio.csv")

In [65]:
df.head()

,año,convocatoria,opcion,ejercicio,tema,tipo_ejercicio
0,2025,Junio,Opción B,Ejercicio 2B,Cinética,Orden de reacción
1,2025,Junio,Opción B,Ejercicio 2B,Cinética,Unidades de la constante de velocidad
2,2025,Junio,Opción B,Ejercicio 2B,Cinética,Factores que afectan a la velocidad
3,2025,Junio,Opción B,Ejercicio 2B,Cinética,Comparación de velocidades de generación/consumo
4,2025,Junio,Opción A,Ejercicio 3A,Equilibrio químico,Equilibrio heterogéneo con cantidad de sólido

In [88]:
df.shape

(295, 6)

In [69]:
df.ejercicio.unique()

<StringArray>
[      'Ejercicio 2B',       'Ejercicio 3A',       'Ejercicio 2A',
       'Ejercicio B2',       'Ejercicio C1',       'Ejercicio B6',
        'Ejercicio 3',        'Ejercicio 5',        'Ejercicio 4',
 'Equilibrio Químico',           'Cinética',               'tema']
Length: 12, dtype: str

In [ ]:
subset1 = df[df.ejercicio.str.contains("Equilibrio")

,año,convocatoria,opcion,ejercicio,tema,tipo_ejercicio
251,2009,Septiembre,Opción B - Ejercicio 5,Equilibrio Químico,Kc y Kp: cálculo numérico,NaN
275,2001,Junio,Opción B - Ejercicio 6,Equilibrio Químico,Cálculo de Kc y Kp + Cálculo de concentracione...,NaN
249,2009,Reserva 3,Opción A - Ejercicio 6,Equilibrio Químico,Equilibrio heterogéneo - cálculo cantidad de s...,NaN

In [91]:
df.sample(5)

,año,convocatoria,opcion,ejercicio,tema,tipo_ejercicio
293,2000,Reserva 4,NaN,"Opción A, Ejercicio 6",Equilibrio Químico,Cálculo de Kp a partir de concentraciones + Cá...
54,2023,Julio,Opción C,Ejercicio C1,Equilibrio químico,Cálculo de Kc y Kp
109,2020,Septiembre,Opción B,Ejercicio B6,Cinética,Valor de la constante cinética o velocidad
77,2021,Junio,Opción C,Ejercicio C1,Equilibrio químico,Cálculo de Kc y Kp
210,2005,Reserva 1,NaN,"Opción B, Ejercicio 5",Equilibrio Químico,Grado de disociación (alfa incógnita) - cálcul...

In [92]:
df.tema.unique()

<StringArray>
[                                                                       'Cinética',
                                                              'Equilibrio químico',
                                       'Ecuación de velocidad - verdadero o falso',
                           'Ecuación de velocidad y cálculo numérico de velocidad',
                         'Órdenes de reacción y unidades de la constante cinética',
                                                 'Catalizador - verdadero o falso',
                       'Ecuación de velocidad y factores que afectan la velocidad',
                            'Ecuación de velocidad - verdadero o falso y unidades',
          'Orden de reacción a partir de unidades y cálculo numérico de velocidad',
                                      'Diagrama entálpico y energía de activación',
                           'Orden de reacción y factores que afectan la velocidad',
                           'Orden de reacción y unidades de la constante cinética',
                                       'Orden de reacción y ecuación de velocidad',
                                  'Orden de reacción - verdadero/falso conceptual',
                       'Orden de reacción y ecuación de velocidad + unidades de k',
                'Factores que afectan a la velocidad - verdadero/falso conceptual',
                                               'Orden de reacción + unidades de k',
                                                                  'tipo_ejercicio',
                        'Diagrama entálpico / energía de activación / catalizador',
                 'Diagrama entálpico / energía de activación (lectura de gráfica)',
 'Diagrama entálpico / energía de activación (lectura de gráfica con catalizador)',
                                      'Diagrama entálpico / energía de activación',
              'Conceptos teóricos (V/F sobre factores que afectan a la velocidad)',
                                                              'Equilibrio Químico']
Length: 24, dtype: str

In [15]:
df.tema = "ácido base"

In [29]:
df = df.sort_values(["año", "convocatoria"]).reset_index(drop=True)

In [38]:
df.año.describe()

count     248.000000
mean     2012.096774
std         7.393968
min      2000.000000
25%      2006.000000
50%      2012.000000
75%      2019.000000
max      2025.000000
Name: año, dtype: float64

In [37]:
df.dtypes

año               int64
convocatoria        str
ejercicio           str
tema                str
tipo_ejercicio      str
dtype: object

In [36]:
df.año = df.año.astype(int)

In [42]:
df.sample(10)

,año,convocatoria,ejercicio,tema,tipo_ejercicio
82,2008,Junio,Ejercicio B4,ácido base,Neutralización ácido-base fuerte (volumen de N...
228,2023,Junio,Ejercicio C3,ácido base,pH ácido débil | Ka | Grado de disociación | D...
172,2017,Reserva 3,Opción B - Ejercicio 3,ácido base,Verdadero/Falso y cuestiones teóricas
146,2014,Septiembre,Opción B - Ejercicio 5,ácido base,"Equilibrio ácido débil (Ka, α, pH) + Kb base c..."
170,2017,Reserva 2,Opción B - Ejercicio 3,ácido base,Hidrólisis de sales (estimación cualitativa de...
198,2020,Reserva 1,Ejercicio C3,ácido base,pH ácido débil | Ka | Kb base conjugada | Conc...
227,2023,Junio,Ejercicio B4,ácido base,Teoría Brønsted-Lowry | pH base débil | Verdad...
199,2020,Reserva 2,Ejercicio C3,ácido base,Disoluciones comerciales | pH base fuerte | Ne...
103,2010,Junio,Opción B - Ejercicio 4,ácido base,Verdadero/Falso y cuestiones teóricas
134,2013,Reserva 3,Opción A - Ejercicio 5,ácido base,Molaridad a partir de densidad/riqueza + Neutr...

In [46]:
df.tipo_ejercicio = df.tipo_ejercicio.apply(lambda x : x.replace("Verdadero/Falso", "Verdadero / Falso"))

In [62]:
df.to_csv("ácido_base.csv", index = False)

In [49]:
df.head()

,año,convocatoria,ejercicio,tema,tipo_ejercicio
0,2000,Junio,Opción A - Ejercicio 4,ácido base,Pares ácido-base conjugados según Brønsted-Low...
1,2000,Junio,Opción B - Ejercicio 6,ácido base,Equilibrio ácido débil: cálculo de masa a part...
2,2000,Reserva 1,Opción A - Ejercicio 3,ácido base,Hidrólisis de sales: color de indicador (estim...
3,2000,Reserva 1,Opción B - Ejercicio 6,ácido base,Equilibrio ácido débil: pH y grado de disociación
4,2000,Reserva 2,Opción A - Ejercicio 3,ácido base,Hidrólisis de NH₄⁺: equilibrio de Brønsted y e...

In [58]:
df["asignatura"] = "química"

In [59]:
df.columns

Index(['año', 'convocatoria', 'ejercicio', 'tema', 'tipo_ejercicio',
       'asignatura'],
      dtype='str')

In [61]:
cols = ["asignatura", "tema", "año", "convocatoria", "ejercicio", "tipo_ejercicio"]
df = df.loc[:, cols]