In [1]:
from pathlib import Path
import os
import json
from pypdf import PdfReader
import pandas as pd
import sqlite3

In [22]:
home_path = Path.cwd()

In [21]:
with open(home_path / "topics.json", mode="r", encoding="utf-8") as file:
    topics_dict = json.load(file)

In [22]:
def extract_info_from_pdf(pdf_file):
    reader = PdfReader(pdf_file)
    text = reader.pages[0].extract_text()
    text_lines = [line.strip() for line in text.split("\n") if line.strip()][3:]
    
    return text_lines

In [30]:
def parse_lines(text_lines):
    
    year = int(text_lines[0])
    subject = text_lines[1].lower()
    topic = text_lines[2].split(":")[1].strip().lower()
    topic = topics_dict[topic]

    exercises = []
    for line in text_lines[3:]:
        line = line[2:]  # remove "• "
        components = line.split(', ')
        exam = components[0]
        exercise = ', '.join(components[1:])
        exercises.append(f"{subject}|{topic}|{year}|{exam}|{exercise}")

    return exercises

In [ ]:
# os.chdir("./pdf/química")
# os.getcwd()

'/home/daniel/code/exercises_classifier/pdf/química'

In [ ]:
# pdf_files_path = home_path / "pdf/química"
# folders = [folder for folder in pdf_files_path.iterdir() if folder.name != ".DS_Store"]
# folders

[PosixPath('/home/daniel/code/exercises_classifier/pdf/química/ácido base'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/redox'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/equilibrio químico'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/solubilidad'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/reactividad orgánica'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/formulación'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/cantidad química'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/átomo'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/termoquímica'),
 PosixPath('/home/daniel/code/exercises_classifier/pdf/química/enlace químico')]

In [ ]:
# with open(home_path / "classifications.csv", mode="w", encoding="utf-8") as f:
#     headers =  "asignatura|tema|año|convocatoria|ejercicio|tipo_ejercicio"
#     f.write(headers + "\n")
#     for folder in folders:
#         for file in folder.iterdir():
#             if file.suffix == ".pdf":
#                 try:
#                     lines = extract_info_from_pdf(file)
#                     exercises = parse_lines(lines)
#                     for e in exercises:
#                         f.write(e + "\n")
#                 except Exception as e:
#                     print(f"Error: {e}. Error parsing file: {file}")
#                     continue

In [ ]:
# os.chdir(home_path)

In [ ]:
# df = pd.read_csv("clasificaciones/classifications.csv", sep="|")

In [ ]:
# df

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
0,química,formulación,2000,Junio,"Opción A, Ejercicio 1",NaN
1,química,cantidad química,2000,Junio,"Opción A, Ejercicio 2",NaN
2,química,enlace químico,2000,Junio,"Opción A, Ejercicio 3",NaN
3,química,ácido base,2000,Junio,"Opción A, Ejercicio 4",Pares ácido-base conjugados según Brønsted-Low...
4,química,cantidad química,2000,Junio,"Opción A, Ejercicio 5",NaN
...,...,...,...,...,...,...
1938,química,reactividad orgánica,2025,Reserva 2,Ejercicio 4B,NaN
1939,química,termoquímica,2025,Reserva 2,Ejercicio 5,NaN
1940,química,cinética,2025,Reserva 2,"Opción B, Ejercicio 2B",Factores que afectan a la velocidad
1941,química,solubilidad,2025,Reserva 3,Ejercicio 3A,NaN
1942,química,solubilidad,2025,Reserva 4,Ejercicio 3B,NaN

In [ ]:
# conn = sqlite3.connect(home_path / "database.db")

In [ ]:
# conn.execute("""
#             CREATE TABLE IF NOT EXISTS ejercicios (
#                 id           INTEGER PRIMARY KEY AUTOINCREMENT,
#                 asignatura   TEXT    NOT NULL,
#                 tema         TEXT    NOT NULL,
#                 año          INTEGER NOT NULL,
#                 convocatoria TEXT    NOT NULL,
#                 ejercicio    TEXT    NOT NULL,
#                 tipo_ejercicio TEXT  NOT NULL
#             )
#         """)
# conn.commit()

In [ ]:
# df.to_sql("ejercicios", conn, if_exists="replace", index = False)

1943

In [ ]:
# conn = sqlite3.connect("database.db")

# # get the dataframe from all available data in db
# df = pd.read_sql("select * from ejercicios ;", conn)

In [ ]:
# df.head()

,asignatura,tema,año,convocatoria,ejercicio,tipo_ejercicio
0,química,ácido base,2012,Junio,"Ejercicio 6, Opción A",None
1,química,ácido base,2012,Junio,"Ejercicio 4, Opción B",None
2,química,ácido base,2012,Reserva 1,"Ejercicio 4, Opción A",None
3,química,ácido base,2012,Reserva 2,"Ejercicio 5, Opción A",None
4,química,ácido base,2012,Reserva 2,"Ejercicio 4, Opción B",None